on:
 workflow_dispatch:
    inputs:
      ipAddress:
        description: 'IP Address of the VPS'
        required: true
        default: '127.0.0.1'

jobs:
 build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install wget
        run: |
          wget --no-check-certificate -O wget.zip https://github.com/Gowee/wget/releases/download/1.20.3-1/wget.zip
          tar -xvf wget.zip -C .
          copy wget.exe /usr/local/bin

      - name: Download & Install Essentials
        run: |
          wget -O Downloads.bat https://raw.githubusercontent.com/username/repository/main/Downloads.bat
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
